title: And The Elephants
email: contact@andtheelephants.com
description: >-
  We are an alternative rock band based in Santiago, Chile. Our first LP &quot;The Procession&quot; is the result of more than three years in a search for a unique concept and sound.
baseurl: ""
url: https://andtheelephants.com
twitter:
  username: AndTheElephants
social:
  name: And The Elephants
  links:
    - https://twitter.com/AndTheElephants
    - https://www.facebook.com/andtheelephants
    - https://www.instagram.com/andtheelephants/
    - https://andtheelephants.bandcamp.com
    - https://www.youtube.com/channel/UCijafLtIiZUJXXMekl40-mw
source: source
destination: docs
