title: And The Elephants Banda Chilena de Rock Alternativo y Conceptual
description: >
    And The Elephants banda de rock basada en Santiago de Chile. Su primer LP &quot;The Procession&quot; es el resultado de cerca de tres a&ntilde;os en b&uacute;squeda de un sonido &uacute;nico.
url: https://andtheelephants.com
baseurl: ""
logo: andtheelephants.<b>com</b>
owner:
  email: contact@andtheelephants.com
  facebook:
    show: true
    name: And The Elephants
    url: http://facebook.com/andtheelephants
sass:
  sass_dir: _sass
  style: compressed
defaults:
  -
    scope:
      path: ""
    values:
      layout: custom
plugins:
  - jekyll-sitemap
